### PR TITLE
Add invitation form

### PR DESCRIPTION
**Pull request by himkt**
Googleフォームを埋め込み

### CODE REVIEW

**Comment by himkt** [comment]
@nzw0301 please review

**Comment by nzw0301** [comment]
- Could you show a screenshot of form?
- Do you think that DeepLearning page does not need this form ?

**Comment by himkt** [comment]
It looks like...
screen shot 2017-05-12 at 15 35 39


I removed the link to google form in /DeepLearning __because__ it's enough to locate the link on /about.
We can navigate people who are interested in joining slack channel (not only deep learning study group).
Of course, I think it's OK to put the invitation link on /DeepLearning.
I want you to let me know your think 😄

**Comment by himkt** [comment]
Or, I think it's also good to add the page (e.g. slis-ml.github.io/invitation)

**Comment by nzw0301** [comment]
OK

**Comment by nzw0301** [comment]
OK. I agree with you.

**Pull request merged**
